# This is a basic workflow to help you get started with Actions

name: bcm53xx-generic

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id
    
    env:
      #TARGET: bcm53xx
      #SUBTARGET: generic
      #TARGET_HOST: 
      URL: https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic/openwrt-sdk-bcm53xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Install dependencies
      run: |
        cores=$(cat /proc/cpuinfo|grep processor|wc -l)
        b="vvb"
        echo "$cores"
    
    - name: Install UPX
      run: |
        echo "$cores"
        echo "$b"
