# This is a basic workflow to help you get started with Actions
# 适用于K3路由器其它的可能需要稍微修改编译代码
name: bcm53xx-generic

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id
    
    env:
      #TARGET: bcm53xx
      #SUBTARGET: generic
      GO_OS: linux
      GO_ARCH: arm
      URL: https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic/openwrt-sdk-bcm53xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Install dependencies
      run: |
        #sudo -E apt-get -qq update
        #sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion git-core gcc-multilib libelf-dev autoconf automake libtool wget curl
        #sudo -E apt-get -qq autoremove --purge
        #sudo -E apt-get -qq clean
        cd ${HOME}
    
    - name: Install UPX
      run: |
        wget --no-check-certificate --quiet --continue --show-progress https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
        tar xvJf upx-3.96-amd64_linux.tar.xz
        sudo mv -f upx-3.96-amd64_linux/upx /usr/local/bin
        rm -rf upx-3.96-amd64_linu*
        
    - name: Prepare Golang
      run: |
        #Download Latest Go
        echo "Finding latest version of Go for AMD64..."
        latest_version="$(wget -qO- https://golang.org/dl/|grep 'download downloadBox' | grep -oP '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)"
        [ -z ${latest_version} ]&&exit 127
        echo "Downloading latest Go for AMD64: ${latest_version}"
        wget --quiet --continue --show-progress https://dl.google.com/go/go${latest_version}.linux-amd64.tar.gz
        [ $? -ne 0 ]&&exit $?
        sudo tar -C /usr/local -xzf go${latest_version}.linux-amd64.tar.gz
        [ $? -ne 0 ]&&exit $?
        rm -f go${latest_version}.linux-amd64.tar.gz
        
    - name: Prepare Toolchain
      run: |
        wget --no-check-certificate --quiet --continue --show-progress ${URL}
        [ $? -ne 0 ]&&exit $?
        tar xvJf openwrt-sdk-*.tar.xz
        [ $? -ne 0 ]&&exit $?
        rm -f ${URL##*/}

    - name: Build
      run: |
        cores=$(cat /proc/cpuinfo|grep processor|wc -l)
        dirn=$(pwd) #主目录
        dirn1=${URL##*/}
        dirn1=${dirn1%*${dirn1:(-7)}} 
        if [ -d ${dirn1} ]; then
          echo "#工具链解压文件夹 ${dirn1}"
        else
          echo "没有识别工具链解压文件夹!"
          exit 127
        fi
        cd ${dirn1}
        for i in staging_dir/* ;do
          [[ ${i##*/} != "host" ]]&&dirn2=${i##*/}
        done
        if [ ${dirn2} ]; then
          echo "#编译器存放目录 ${dirn2}"
        else
          echo "没有识别出编译器存放目录!"
          exit 127
        fi
        for i in staging_dir/${dirn2}/bin/*-gcc; do
          target_host=$(echo ${i##*/}|grep -oP "[A-Za-z0-9]+\-[A-Za-z0-9]+\-[A-Za-z0-9]+")
        done
        if [ ${target_host} ]; then
          echo "#编译器平台为 ${target_host}"
        else
          echo "没有识别出编译器!"
          exit 127
        fi
        export PATH=$PATH:/usr/local/go/bin:${dirn}/${dirn1}/staging_dir/${dirn2}/bin
        export STAGING_DIR=${dirn}/${dirn1}
        mkdir -p ${HOME}/ssl
        git clone https://github.com/openssl/openssl
        cd openssl
        git submodule update --init --recursive
        ./Configure \
        no-asm \
        --cross-compile-prefix=${target_host}- \
        --prefix=${HOME}/ssl \
        linux-armv4
        make -j ${cores:=1}
        sudo make install_sw
        make clean
